### ISSUE TITLE
Syntax for using `BatchNorm` with `filter_jit` and `filter_grad_value`?

### ISSUE THREAD

**Issue by paganpasta** [patrick-kidger/equinox#161]
Hi,

I am not sure if I am using the proper way to compute gradients on a model with `BatchNorm`. Followed the example provided for `BatchNorm` and added the `axis_name=('batch')`. But getting the error 
```
Traceback (most recent call last):
  File "tests/test_dummy.py", line 34, in <module>
    loss, model, opt_state, grads = make_step(net, jnp.asarray(xs), jnp.asarray(ys), opt_state)
  File "/home/AS3895/PycharmProjects/equinox/equinox/jit.py", line 95, in __call__
    return __self._fun_wrapper(False, args, kwargs)
  File "/home/AS3895/PycharmProjects/equinox/equinox/jit.py", line 91, in _fun_wrapper
    dynamic_out, static_out = self._cached(dynamic, static)
  File "/home/AS3895/PycharmProjects/equinox/equinox/jit.py", line 38, in fun_wrapped
    out = fun(*args, **kwargs)
  File "tests/test_dummy.py", line 22, in make_step
    loss, grads = compute_loss(model, x, y)
  File "/home/AS3895/PycharmProjects/equinox/equinox/grad.py", line 30, in __call__
    return fun_value_and_grad(diff_x, nondiff_x, *args, **kwargs)
  File "/home/AS3895/PycharmProjects/equinox/equinox/grad.py", line 27, in fun_value_and_grad
    return __self._fun(_x, *_args, **_kwargs)
  File "tests/test_dummy.py", line 17, in compute_loss
    pred_y = jax.vmap(model, axis_name=('batch'))(x)
  File "/home/AS3895/PycharmProjects/equinox/equinox/nn/composed.py", line 128, in __call__
    x = layer(x, key=key)
  File "/home/AS3895/PycharmProjects/equinox/equinox/experimental/batch_norm.py", line 158, in __call__
    running_state = lax.cond(
  File "/home/AS3895/miniconda3/envs/equinox/lib/python3.8/site-packages/jax/experimental/host_callback.py", line 1336, in _outside_call_jvp_rule
    raise NotImplementedError("JVP rule is implemented only for id_tap, not for call.")
NotImplementedError: JVP rule is implemented only for id_tap, not for call.
```

A minimal code to reproduce this behaviour is here
```python
import equinox as eqx
import jax
import jax.numpy as jnp
import jax.random as jrandom
import numpy as np
import optax


net = eqx.nn.Sequential([
    eqx.nn.Linear(in_features=3, out_features=1, key=jrandom.PRNGKey(0)),
    eqx.experimental.BatchNorm(input_size=1, axis_name="batch"),
])


@eqx.filter_value_and_grad
def compute_loss(model, x, y):
    pred_y = jax.vmap(model, axis_name="batch")(x)
    return -jnp.mean(y-pred_y)


@eqx.filter_jit
def make_step(model, x, y, opt_state):
    loss, grads = compute_loss(model, x, y)
    updates, opt_state = optim.update(grads, opt_state)
    model = eqx.apply_updates(model, updates)
    return loss, model, opt_state, grads


optim = optax.adam(0.1)
opt_state = optim.init(eqx.filter(net, eqx.is_array))

xs = np.random.uniform(-1, 1, size=(5, 3))
ys = np.random.randint(0, 1, 5)

loss, model, opt_state, grads = make_step(net, jnp.asarray(xs), jnp.asarray(ys), opt_state)
```

**Comment by patrick-kidger** [comment]
Fixed in #162!

**Comment by paganpasta** [comment]
Wow, thanks for the quick fix! Seems to be working for few cases I tried.

It looks like the issue was grad being computed for `first_time` attribute.

**Comment by patrick-kidger** [comment]
So `first_time` is a boolean. (It can't have a gradient.) It's actually `batch_state` that had the gradient. We actually don't need the gradient here at all; the `like` argument is just so we can create a PyTree with the appropriate shape/structure/batch-tracers etc.
