### ISSUE TITLE
`BatchNorm` raises `RuntimeError: Cannot get state before it has been set` when used in a scan

### ISSUE THREAD

**Issue by ciupakabra** [patrick-kidger/equinox#237]
`BatchNorm` raises `RuntimeError: Cannot get state before it has been set` when used in a scan. Minimal working example is given below. Note that calling `vmapped_fun` twice and decorating with `eqx.filter_grad` are both necessary and that swapping `jax.lax.map(bn, xs)` to `jax.vmap(bn)(xs)` doesn't raise.

```python
import jax
import jax.numpy as jnp
import jax.random as jrandom
import equinox as eqx

def fun(bn, xs):
    return jax.lax.map(bn, xs)

@eqx.filter_grad
def vmapped_fun(bn, xss):
    return jnp.mean(jax.vmap(fun, (None, 0), axis_name="batch")(bn, xss))

if __name__=="__main__":
    bn = eqx.experimental.BatchNorm(10, axis_name="batch")
    inp = jrandom.normal(jrandom.PRNGKey(0), (32, 20, 10))

    grad = vmapped_fun(bn, inp)
    grad = vmapped_fun(bn, inp)
```

outputs

```
ERROR:jax.experimental.host_callback:Outside call <jax.experimental.host_callback._CallbackWrapper object at 0x11a530550> threw exception Cannot get state before it has been set.
Traceback (most recent call last):
  File "/Users/andriusovsianas/repos/test/test.py", line 18, in <module>
    grad = vmapped_fun(bn, inp)
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 53, in __call__
    value, grad = __self._fun_value_and_grad(*args, **kwargs)
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 40, in __call__
    return fun_value_and_grad(diff_x, nondiff_x, *args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py", line 1167, in value_and_grad_f
    ans, vjp_py = _vjp(f_partial, *dyn_args, reduce_axes=reduce_axes)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py", line 2656, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py", line 135, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py", line 124, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr_nounits(jvpfun_flat, in_pvals)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 767, in trace_to_jaxpr_nounits
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 37, in fun_value_and_grad
    return __self._fun(_x, *_args, **_kwargs)
  File "/Users/andriusovsianas/repos/test/test.py", line 11, in vmapped_fun
    return jnp.mean(jax.vmap(fun, (None, 0), axis_name="batch")(bn, xss))
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py", line 1682, in vmap_f
    out_flat = batching.batch(
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py", line 167, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/andriusovsianas/repos/test/test.py", line 7, in fun
    return jax.lax.map(bn, xs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1730, in map
    _, ys = scan(g, (), xs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 275, in scan
    out = scan_p.bind(*consts, *in_flat,
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1000, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 2444, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/batching.py", line 350, in process_primitive
    val_out, dim_out = batcher_primitive(vals_in, dims_in, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 755, in _scan_batching_rule
    outs = scan_p.bind(
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1000, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 2444, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py", line 310, in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 485, in _scan_jvp
    out_flat = scan_p.bind(
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1000, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 2444, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 207, in process_primitive
    return custom_partial_eval_rules[primitive](self, *tracers, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 595, in _scan_partial_eval
    out_known = scan_p.bind(
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py", line 1000, in scan_bind
    return core.AxisPrimitive.bind(scan_p, *args, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 2444, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 332, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py", line 712, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py", line 115, in apply_primitive
    return compiled_fun(*args)
  File "/Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py", line 895, in _execute_compiled
    out_flat = compiled.execute(in_flat)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: RuntimeError: Cannot get state before it has been set

At:
  /Users/andriusovsianas/repos/equinox/equinox/experimental/stateful.py(355): _get_state_hcb
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(726): __call__
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(1295): _outside_call_run_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(1164): wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/mlir.py(1579): _wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/mlir.py(1604): _wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py(895): _execute_compiled
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py(115): apply_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(712): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(595): _scan_partial_eval
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py(207): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(485): _scan_jvp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(310): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(755): _scan_batching_rule
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/batching.py(350): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(275): scan
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1730): map
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/test/test.py(7): fun
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py(167): call_wrapped
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(1682): vmap_f
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/test/test.py(11): vmapped_fun
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(37): fun_value_and_grad
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py(167): call_wrapped
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py(767): trace_to_jaxpr_nounits
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/profiler.py(314): wrapper
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(124): linearize
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(135): vjp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(2656): _vjp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(1167): value_and_grad_f
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(40): __call__
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(53): __call__
  /Users/andriusovsianas/repos/test/test.py(18): <module>

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andriusovsianas/repos/test/test.py", line 18, in <module>
    grad = vmapped_fun(bn, inp)
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 53, in __call__
    value, grad = __self._fun_value_and_grad(*args, **kwargs)
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 40, in __call__
    return fun_value_and_grad(diff_x, nondiff_x, *args, **kwargs)
  File "/Users/andriusovsianas/repos/equinox/equinox/grad.py", line 37, in fun_value_and_grad
    return __self._fun(_x, *_args, **_kwargs)
  File "/Users/andriusovsianas/repos/test/test.py", line 11, in vmapped_fun
    return jnp.mean(jax.vmap(fun, (None, 0), axis_name="batch")(bn, xss))
  File "/Users/andriusovsianas/repos/test/test.py", line 7, in fun
    return jax.lax.map(bn, xs)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: RuntimeError: Cannot get state before it has been set

At:
  /Users/andriusovsianas/repos/equinox/equinox/experimental/stateful.py(355): _get_state_hcb
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(726): __call__
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(1295): _outside_call_run_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/experimental/host_callback.py(1164): wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/mlir.py(1579): _wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/mlir.py(1604): _wrapped_callback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py(895): _execute_compiled
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/dispatch.py(115): apply_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(712): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(595): _scan_partial_eval
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py(207): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(485): _scan_jvp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(310): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(755): _scan_batching_rule
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/batching.py(350): process_primitive
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(332): bind_with_trace
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/core.py(2444): bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1000): scan_bind
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(275): scan
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/lax/control_flow/loops.py(1730): map
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/test/test.py(7): fun
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py(167): call_wrapped
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(1682): vmap_f
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/test/test.py(11): vmapped_fun
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(37): fun_value_and_grad
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/linear_util.py(167): call_wrapped
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/partial_eval.py(767): trace_to_jaxpr_nounits
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/profiler.py(314): wrapper
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(124): linearize
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/interpreters/ad.py(135): vjp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(2656): _vjp
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/api.py(1167): value_and_grad_f
  /Users/andriusovsianas/miniconda/lib/python3.10/site-packages/jax/_src/traceback_util.py(162): reraise_with_filtered_traceback
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(40): __call__
  /Users/andriusovsianas/repos/equinox/equinox/grad.py(53): __call__
  /Users/andriusovsianas/repos/test/test.py(18): <module>
```

**Comment by patrick-kidger** [comment]
Closing as the old experimental `BatchNorm` has been removed -- we now have a stable `eqx.nn.BatchNorm` implementation.
