### ISSUE TITLE
`JaxStackTraceBeforeTransformation` in hyper-parameter optimisation

### ISSUE THREAD

**Issue by LouisDesdoigts** [patrick-kidger/equinox#245]
Hey so I am running into an odd `JaxStackTraceBeforeTransformation` error when trying to optimize hyper-parameters. This works within the Jax framework, but throws an error when within the equinox framework. The error seems to arise when the inner optimized parameter is cast to complex.

 Here is the working pure-jax example:

```py
import jax
import jax.numpy as np

def model_fn(x):
    """Create complex array using input"""
    array = np.linspace(-x, x, 10)
    return np.abs(1j*array)

@jax.value_and_grad
def inner_loss_fn(x, data):
    return np.square(model_fn(x) - data).sum()

@jax.value_and_grad
def loss_fn(lr, x, data):
    for i in range(10):
        inner_loss, grad = inner_loss_fn(x, data)
        x = x - lr * grad
    return x

data = model_fn(0.)
inner_loss, inner_grad = inner_loss_fn(1., data)
loss, grad = loss_fn(1., 1., data)
```

All of the values returned here are non-nan and works as expected. However when this wrapped into a light `equinox.Module`, an error is thrown.

```py
import equinox as eqx
class TestClass(eqx.Module):
    x : float

    def __init__(self, x):
        self.x = np.array(x)
    
    def model(self):
        return model_fn(self.x)

model = TestClass(1.)
@eqx.filter_value_and_grad(arg=jax.tree_map(lambda _: True, model))
def eqx_inner_loss_fn(model, data):
    return np.square(model.model() - data).sum()

@jax.value_and_grad
def eqx_loss_fn(lr, model, data):
    step_fn = lambda grads, lr: jax.tree_map(lambda leaf: -lr * leaf, grads)
    for i in range(10):
        inner_loss, grads = eqx_inner_loss_fn(model, data)
        step = step_fn(grads, lr)
        model = eqx.apply_updates(model, step)
    return inner_loss

inner_loss, inner_grad = eqx_inner_loss_fn(model, data)
loss, grads = eqx_loss_fn(1., model, data) # Error thrown on this line
```

Here is the full stack trace:

```
Traceback (most recent call last):
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 14, in <module>
    @jax.value_and_grad
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 16, in loss_fn
    for i in range(10):
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 12, in inner_loss_fn
    return np.square(model_fn(x) - data).sum()
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 8, in model_fn
    return np.abs(np.exp(1j*array))
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/numpy/ufuncs.py", line 195, in absolute
    return x if dt == np.bool_ or dtypes.issubdtype(dt, np.unsignedinteger) else lax.abs(x)
jax._src.source_info_util.JaxStackTraceBeforeTransformation: TypeError: Cannot interpret 'Zero(ShapedArray(complex64[10]))' as a data type

The preceding stack trace is the source of the JAX operation that, once transformed by JAX, triggered the following exception.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 53, in <module>
    loss, grads = eqx_loss_fn(1., model, data)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/equinox/grad.py", line 40, in __call__
    return fun_value_and_grad(diff_x, nondiff_x, *args, **kwargs)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/api.py", line 1156, in value_and_grad_f
    g = vjp_py(lax_internal._one(ans))
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/tree_util.py", line 292, in __call__
    return self.fun(*args, **kw)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/api.py", line 2523, in _vjp_pullback_wrapper
    ans = fun(*args)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/tree_util.py", line 292, in __call__
    return self.fun(*args, **kw)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/ad.py", line 140, in unbound_vjp
    arg_cts = backward_pass(jaxpr, reduce_axes, True, consts, dummy_args, cts)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/ad.py", line 240, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/ad.py", line 625, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/core.py", line 1939, in bind
    return call_bind(self, fun, *args, **params)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/core.py", line 1955, in call_bind
    outs = top_trace.process_call(primitive, fun_, tracers, params)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/core.py", line 701, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/dispatch.py", line 234, in _xla_call_impl
    compiled_fun = xla_callable(fun, device, backend, name, donated_invars,
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/dispatch.py", line 342, in _xla_callable_uncached
    return lower_xla_callable(fun, device, backend, name, donated_invars, False,
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/dispatch.py", line 428, in lower_xla_callable
    jaxpr, out_type, consts = pe.trace_to_jaxpr_final2(
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 2080, in trace_to_jaxpr_final2
    jaxpr, out_type, consts = trace_to_subjaxpr_dynamic2(fun, main, debug_info)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/partial_eval.py", line 2030, in trace_to_subjaxpr_dynamic2
    ans = fun.call_wrapped(*in_tracers_)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/linear_util.py", line 168, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/interpreters/ad.py", line 246, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 2017, in _conj_transpose_rule
    return [conj(t)]
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/lax/lax.py", line 407, in conj
    return conj_p.bind(x, input_dtype=_dtype(x))
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/jax/_src/dtypes.py", line 445, in dtype
    dt = np.result_type(x)
  File "<__array_function__ internals>", line 180, in result_type
jax._src.traceback_util.UnfilteredStackTrace: TypeError: Cannot interpret 'Zero(ShapedArray(complex64[10]))' as a data type

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/louis/PhD/dLux/sandbox/Deconvolution/example.py", line 53, in <module>
    loss, grads = eqx_loss_fn(1., model, data)
  File "/Users/louis/mambaforge/envs/dlux/lib/python3.10/site-packages/equinox/grad.py", line 40, in __call__
    return fun_value_and_grad(diff_x, nondiff_x, *args, **kwargs)
  File "<__array_function__ internals>", line 180, in result_type
TypeError: Cannot interpret 'Zero(ShapedArray(complex64[10]))' as a data type
```

So I have played around a little and found that if in `model_fn` if we simply return `return np.abs(array)` (ie not casting it to complex) then this error is not raised. This error is also raised when using `eqx.filter_value_and_grad` on `eqx_loss_fn`. 

I am very much at a loss about this error, so any help is appreciated!

Cheers,
Louis

**Comment by LouisDesdoigts** [comment]
Oh and versions:
jax: 0.3.23
jaxlib: 0.3.22
equinox: 0.9.2

**Comment by patrick-kidger** [comment]
Your `loss_fn` is returning `x`, but your `eqx_loss_fn` is returning `inner_loss`.

That said it also looks like the error is due to a bug in JAX, namely that the transpose rule for `jnp.conj` doens't know how to handle symbolic zeros.

**Comment by LouisDesdoigts** [comment]
Ah yes I thought those functions were mirrored - Can reproduce purely in jax now. Will raise it with the jax team.

Cheers
