### ISSUE TITLE
unable to initialize optimizer state from equinox model

### ISSUE THREAD

**Issue by drasros** [patrick-kidger/equinox#257]
Thanks for this lib!
For some reason, I am unable to initialize state (optax optimizer) from equinox model. 
The below code shows the problem. (with sgd instead of adam, or if I use a simple jnp tensor instead of the equinox model it initializes fine)
Any idea where it can come from ? A version problem maybe ?
Many thanks

```
Python 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import equinox as eqx
>>> import jax.random as jr
>>> import optax
>>> 
>>> model = eqx.nn.MLP(2, 2, 2, 2, key=jr.PRNGKey(0))
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
>>> optim = optax.adam(0.1)
>>> opt_state = optim.init(model)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/optax/_src/combine.py", line 45, in init_fn
    return tuple(fn(params) for fn in init_fns)
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/optax/_src/combine.py", line 45, in <genexpr>
    return tuple(fn(params) for fn in init_fns)
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/optax/_src/transform.py", line 335, in init_fn
    mu = jax.tree_util.tree_map(  # First moment
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/jax/_src/tree_util.py", line 207, in tree_map
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/jax/_src/tree_util.py", line 207, in <genexpr>
    return treedef.unflatten(f(*xs) for xs in zip(*all_leaves))
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/optax/_src/transform.py", line 336, in <lambda>
    lambda t: jnp.zeros_like(t, dtype=mu_dtype), params)
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2039, in zeros_like
    _check_arraylike("zeros_like", a)
  File "/nfs/tools/mlo/asors/anaconda3/envs/jax_mctx2/lib/python3.10/site-packages/jax/_src/numpy/util.py", line 345, in _check_arraylike
    raise TypeError(msg.format(fun_name, type(arg), pos))
TypeError: zeros_like requires ndarray or scalar arguments, got <class 'jax._src.custom_derivatives.custom_jvp'> at position 0.

```

**Comment by patrick-kidger** [comment]
See [the FAQ](https://docs.kidger.site/equinox/faq/#optax-is-throwing-an-error).

**Comment by drasros** [comment]
many thanks. Not sure how I missed this...
