### ISSUE TITLE
Can't import equinox 0.10.6 in python 3.9.0

### ISSUE THREAD

**Issue by dieterichlawson** [patrick-kidger/equinox#414]
When I try to import equinox 0.10.6 in python 3.9.0 I get the following error:

```
>>> import equinox as eqx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/__init__.py", line 3, in <module>
    from . import internal as internal, nn as nn
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/internal/__init__.py", line 5, in <module>
    from .._compile_utils import (
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/_compile_utils.py", line 12, in <module>
    from ._module import Module
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/_module.py", line 17, in <module>
    from ._tree import tree_equal
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/_tree.py", line 10, in <module>
    from ._filters import is_array
  File "/home/groups/swl1/jdlawson/nast/.env/lib/python3.9/site-packages/equinox/_filters.py", line 11, in <module>
    AxisSpec = Union[bool, Callable[[Any], bool]]
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 243, in inner
    return func(*args, **kwds)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 316, in __getitem__
    return self._getitem(self, parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 421, in Union
    parameters = _remove_dups_flatten(parameters)
  File "/share/software/user/open/python/3.9.0/lib/python3.9/typing.py", line 215, in _remove_dups_flatten
    all_params = set(params)
TypeError: unhashable type: 'list'
```

I'm on a system where I am not an administrator and cannot upgrade the python version, sadly.

**Comment by dieterichlawson** [comment]
After digging around a bit, I seem to be able to import equinox 0.10.5 just fine.

**Comment by patrick-kidger** [comment]
This is a bug with Python `3.9.<something small>`. Ask your administrator to upgrade your Python version.

**Comment by FranzKnut** [comment]
Is equinox compatible with pyhon 3.11? I am facing issues when trying to install using poetry.

**Comment by patrick-kidger** [comment]
It should be compatible with Python 3.11, yes.

**Comment by FranzKnut** [comment]
> Is equinox compatible with pyhon 3.11? I am facing issues when trying to install using poetry.

thanks, this appeared to be an issue with poetry when installing aim at the same time.
