### ISSUE TITLE
Incorrect error handling in error_if

### ISSUE THREAD

**Issue by danielward27** [patrick-kidger/equinox#696]
Installing equinox with:
```bash
pip install equinox jaxlib
```

Then running
```python
import equinox as eqx
import jax

def f(x):
    x = eqx.error_if(x, x < 0, "x must be >= 0")
    return jax.nn.relu(x)

f(jax.numpy.array(-1))
```
Causes an error during error handling:
```
jax.pure_callback failed
Traceback (most recent call last):
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/callback.py", line 77, in pure_callback_impl
    return callback(*args)
           ^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/callback.py", line 65, in __call__
    return tree_util.tree_leaves(self.callback_func(*args, **kwargs))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 70, in raises
    raise EqxRuntimeError(msgs[_index.item()])
equinox._errors.EqxRuntimeError: x must be >= 0
Traceback (most recent call last):
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_jit.py", line 206, in __call__
    return self._call(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_module.py", line 935, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_jit.py", line 200, in _call
    out = self._cached(dynamic_donate, dynamic_nodonate, static)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Generated function failed: CpuCallback error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 229, in error_if
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 250, in branched_error_if
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_jit.py", line 206, in __call__
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_module.py", line 935, in __call__
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_jit.py", line 200, in _call
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/traceback_util.py", line 179, in reraise_with_filtered_traceback
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/pjit.py", line 298, in cache_miss
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/pjit.py", line 176, in _python_pjit_helper
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/core.py", line 2788, in bind
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/core.py", line 425, in bind_with_trace
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/core.py", line 913, in process_primitive
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/pjit.py", line 1488, in _pjit_call_impl
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/pjit.py", line 1471, in call_impl_cache_miss
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/pjit.py", line 1427, in _pjit_call_impl_python
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/profiler.py", line 335, in wrapper
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/interpreters/pxla.py", line 1205, in __call__
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/interpreters/mlir.py", line 2466, in _wrapped_callback
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/callback.py", line 219, in _callback
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/callback.py", line 80, in pure_callback_impl
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/jax/_src/callback.py", line 65, in __call__
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 70, in raises
EqxRuntimeError: x must be >= 0
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 229, in error_if
    return branched_error_if(x, pred, 0, [msg], on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_errors.py", line 250, in branched_error_if
    return branched_error_if_impl_jit(x, pred, index, msgs, on_error=on_error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dw16200/miniconda3/envs/eqx/lib/python3.12/site-packages/equinox/_jit.py", line 215, in __call__
    msg, _ = msg.rsplit("\n\nAt:\n", 1)
    ^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by danielward27** [comment]
If I go back to jax/jaxlib==0.4.25, the issue does not occur

**Comment by patrick-kidger** [comment]
Fixed!
