### ISSUE TITLE
Error with data sharding 

### ISSUE THREAD

**Issue by andremfreitas** [patrick-kidger/equinox#738]
Hi,

I have been facing an error that I cannot understand and resolve when trying to port my ML code to multiple devices (data parallelism).

The error faced is: 

```
Traceback (most recent call last):
  File "/home/ids/afreitas/test/mwe.py", line 162, in <module>
    z, y = eqx.filter_shard((z, y), sharding)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/equinox/_sharding.py", line 40, in filter_shard
    dynamic = lax.with_sharding_constraint(dynamic, shardings)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2179, in with_sharding_constraint
    outs = [sharding_constraint_p.bind(xf, sharding=s,
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2179, in <listcomp>
    outs = [sharding_constraint_p.bind(xf, sharding=s,
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 422, in bind
    return self.bind_with_trace(find_top_trace(args), args, params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 425, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/core.py", line 913, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/pjit.py", line 2191, in _sharding_constraint_impl
    return api.jit(_identity_fn, out_shardings=sharding)(x)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 122, in shard_shape
    return _common_shard_shape(self, global_shape)
  File "/home/ids/afreitas/jax/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 68, in _common_shard_shape
    assert len(partitions) == len(global_shape), (len(partitions), len(global_shape))
AssertionError: (1, 3)
```

A MWE for my code is shown here below:

```
import jax
import jax.numpy as jnp
import jax.random as jrandom
import numpy as np
import equinox as eqx
import optax 
from jax import config
config.update("jax_enable_x64", True)
from time import time as timer
import jax.experimental.mesh_utils as mesh_utils
import jax.sharding as jshard

# Fixed Parameters & Useful vectors
N = 10  # Num of shells
nu = 10**-6  # viscosity
dt = 10**-4  # integration step
a, b, c = (1.0, -0.50, -0.50)
k, ek, forcing = [], [], []
for n in range(N):
    k.append(2**n)
    ek.append(jnp.exp(-nu * dt * k[n] * k[n] / 2.0))
    if n == 0:
        forcing.append(1 + 1j)

k_1d = jnp.array(k, dtype=jnp.complex128)
k = jnp.array(k, dtype=jnp.complex128)
ek = jnp.array(ek, dtype=jnp.complex128)
forcing = jnp.array(forcing, dtype=jnp.complex128)
forcing = jnp.concatenate((forcing, jnp.zeros(N - 1)))

batch_size = 256
msteps = 16

k = jnp.transpose(jnp.tile(k, (batch_size, 1)))
ek = jnp.transpose(jnp.tile(ek, (batch_size, 1)))
forcing = jnp.transpose(jnp.tile(forcing, (batch_size, 1)))

# Dummy data
u_re = np.random.rand(N, 256, 1000)
u_im = np.random.rand(N, 256, 1000)
u = u_re + u_im*1j
n_ics0 = u.shape[1]
num_steps0 = u.shape[2]

# Replaced the original function with some dummy function
@jax.jit
def G(u):

    coupling1 = np.random.rand(20)
    coupling2 = np.random.rand(20)
    coupling = coupling1 + coupling2 * 1j

    return coupling

# Replaced the original function with some dummy function
@jax.jit
def RK4(u):
    return u


seed = 42
model = eqx.nn.MLP(2, 2, 16, 2, key=jax.random.PRNGKey(seed))

@jax.jit
def make_step(i, state_tuple):
    aux, u, model = state_tuple
    aux = RK4(u[:, :, i])
    aux_re = jnp.transpose(jnp.real(aux))
    aux_im = jnp.transpose(jnp.imag(aux))

    aux_tot = jnp.concatenate([jnp.expand_dims(aux_re, axis=-1), jnp.expand_dims(aux_im, axis=-1)], axis = -1)
    
    pred = jax.vmap(jax.vmap(model))(aux_tot)
    
    aux_tot_updt = aux_tot + pred
    aux_updt = jnp.transpose(jax.lax.complex(aux_tot_updt[:, :, 0], aux_tot_updt[:, :, 1]))

    u = u.at[:, :, i+1].set(aux_updt)

    return aux, u, model


@jax.value_and_grad
def one_step(model, msteps, aux, u, gt_tensor):
    aux, u, model = jax.lax.fori_loop(0, msteps-1, make_step, (aux, u, model))
    loss = jax.numpy.mean(jax.numpy.square(jax.numpy.abs(u - gt_tensor)))
    return loss


@eqx.filter_jit
def updt_step(model, msteps, aux, u, gt_tensor, opt_state, sharding):
    replicated = sharding.replicate()
    model, opt_state = eqx.filter_shard((model, opt_state), replicated)
    aux, u, gt_tensor = eqx.filter_shard((aux, u, gt_tensor), sharding)
    loss, grads = one_step(model, msteps, aux, u, gt_tensor)
    updates, opt_state = optim.update(grads, opt_state)
    model = eqx.apply_updates (model, updates)
    model, opt_state = eqx.filter_shard((model, opt_state), replicated)

    return loss, model, opt_state


lr0 = 1e-4
optim = optax.adam(learning_rate = lr0)
opt_state = optim.init(eqx.filter(model, eqx.is_inexact_array))

# Parallelization stuff
num_devices = len(jax.devices())
print(f"Num GPUs: {num_devices}")
devices = mesh_utils.create_device_mesh((1,num_devices))
sharding = jshard.PositionalSharding(devices)
replicated = sharding.replicate()

model = eqx.filter_shard(model, replicated)


def dataloader(arrays, batch_size):
    dataset_size = arrays[0].shape[0]
    assert all(array.shape[0] == dataset_size for array in arrays)
    indices = np.arange(dataset_size)
    perm = np.random.permutation(indices)
    start = 0
    end = batch_size
    while end <= dataset_size:
        batch_perm = perm[start:end]
        yield tuple(array[batch_perm] for array in arrays)
        start = end
        end = start + batch_size

gt_tensor = jnp.transpose(u, (1,0,2))
ic = u[:, :, 0]

print('Finshed preparing data. \n About to enter training loop')

losses = []
epochs = [1, 1, 1]

msteps_sched = [2, 4, 8]

start = timer()


for j in range(len(epochs)):
    msteps = msteps_sched[j]
    print(f"\nmsteps = {msteps}\n")

    gt_tensor = jnp.reshape(gt_tensor, (int(n_ics0 * num_steps0 / msteps), N, msteps))

    n_ics = gt_tensor.shape[0]

    u = jnp.zeros((n_ics, N, msteps), dtype = jnp.complex128)
    u = u.at[:,:, 0].set(gt_tensor[:, :, 0])


    for epoch in range(epochs[j]):
        print(f"Epoch {epoch}")
        step = 0
        iter_data = dataloader((gt_tensor, u), batch_size)
        for (z, y) in iter_data:
            z, y = eqx.filter_shard((z, y), sharding)
            z = jnp.transpose(z, (1, 0, 2))
            x = z[:, :, 0]
            y = jnp.transpose(y, (1, 0, 2))
            loss, model, opt_state = updt_step(model, msteps, x, y, z, opt_state, sharding)
            loss = loss.item()
            print(f'step={step}, loss={loss}')
            losses.append(loss)
            step += 1
end = timer()
print(f"Time = {end - start}s")
```

In terms of versions:
jax                      0.4.26
equinox                  0.11.4
optax                    0.2.2
numpy                    1.26.4

All help is very much appreciated.

Thanks,
Andre

**Comment by patrick-kidger** [comment]
Looking at your stack trace, you can probably reproduce this without Equinox by calling just `lax.with_sharding_constraint`. (This should probably produce a MWE that is about 8 lines long.) Can you do this please?

**Comment by andremfreitas** [comment]
Here is the shorter MWE without equinox:

```
import jax
from jax.experimental import mesh_utils
import jax.sharding as jshard

num_devices = len(jax.devices())
print(f"Num GPUs: {num_devices}")
devices = mesh_utils.create_device_mesh((1,num_devices))
sharding = jshard.PositionalSharding(devices)
replicated = sharding.replicate()

x = jax.random.uniform(jax.random.PRNGKey(42), (256, 20, 1000))

x = jax.lax.with_sharding_constraint(x, sharding)
```

The error is the same as the one reported above.

**Comment by patrick-kidger** [comment]
Great!
In this particular case I'm not sure off the top of my head what is going wrong. But as this now seems to be a pure-JAX issue you could try opening a discussion on the JAX issue tracker instead?

**Comment by andremfreitas** [comment]
Yes, of course. Thanks for the help :)

**Comment by andremfreitas** [comment]
For completeness of this thread, I leave here the solution:
`sharding = jshard.PositionalSharding(devices)`    -->  `sharding = jshard.PositionalSharding(devices).reshape(1, 1, num_devices)`
