### ISSUE TITLE
[Question] Interaction with optax LBFGS optimizer

### ISSUE THREAD

**Issue by bnesposito** [patrick-kidger/equinox#796]
Hi,
I am having trouble implementing optax LBFGS with equinox types. I am trying to run a linear regression model using this notebook https://github.com/ubcecon/ECON622/blob/master/lectures/lectures/examples/linear_regression_jax_equinox.py and changing the optimizer to optax.lbfgs(). Here is the core of the code:

```
def residual(model, x, y):
    y_hat = model(x)
    return (y_hat - y) ** 2

def residuals(model, X, Y):
    batched_residuals = vmap(residual, in_axes=(None, 0, 0))
    return jnp.mean(batched_residuals(model, X, Y))

@eqx.filter_jit
def make_step(model, opt_state, X, Y):     
  loss_value, grads = eqx.filter_value_and_grad(residuals)(model, X, Y)
  resids_closure = lambda x: residual(model, x, Y)
  updates, opt_state = optimizer.update(grads, opt_state, model, value=loss_value, grad=grads, value_fn=resids_closure)
  model = eqx.apply_updates(model, updates)
  return model, opt_state, loss_value
```
I get the following error:

`TypeError: unsupported operand type(s) for @: 'DynamicJaxprTracer' and 'Linear'`

From the traceback, the error shows up when evaluating the resids_closure function. Particularly, when I evaluate model(x) and it tries to multiply weights by x:

```
class MyLinear(eqx.Module):
    weight: jax.Array

    def __init__(self, in_size, out_size, key):
        self.weight = jax.random.normal(key, (out_size, in_size))

    # Equivalent to Pytorch's forward
    def __call__(self, x):
        return self.weight @ x
```

Does anybody have an idea on how to tackle this? Thanks!

**Comment by patrick-kidger** [comment]
From your description is seems possible that you've gotten two arguments the wrong way around, so that you are passing a `Linear` layer in as the input `x`.

I suspect `optimizer.update(..., value_fn=...)` is meant to accept the parameters as input, not data.

**Comment by jlperla** [comment]
Hmm.... having some trouble here still (and also, this is not not using the cached `optax.value_and_grad_from_state` which is part of the performance.

Here is something where shows the current issues I am seeing.  Consider: (1) `eqx.nn.Linear`; (2) a custom `nn.Module`; and (3) a MLP.   And run with LBFGS and with SGD.    Everything works except the MLP+lbfgs.

To replicate: run the following code, then comment/uncomment to swap out the optimizer used (near the top of the file) and you will see the error:

```python
# Takes the baseline version and uses vmap, adds in a learning rate scheduler
import jax
import jax.numpy as jnp
from jax import random
import optax
import equinox as eqx
import jax_dataloader as jdl
from jax_dataloader.loaders import DataLoaderJAX


# LLS loss function with vmap
def residual(model, x, y):
    y_hat = model(x)
    return (y_hat - y) ** 2

def residuals(model, X, Y):
    batched_residuals = jax.vmap(residual, in_axes=(None, 0, 0))
    return jnp.mean(batched_residuals(model, X, Y))


# SWITCH OPTIMIZERS HERE!!!!
# reinitialize
optimizer = optax.sgd(0.001)
#optimizer = optax.lbfgs()


N = 500  # samples
M = 2
sigma = 0.0001
key = random.PRNGKey(42)
key, *subkey = random.split(key, num=4)
theta = random.normal(subkey[0], (M,))
X = random.normal(subkey[1], (N, M))
Y = X @ theta + sigma * random.normal(subkey[2], (N,))  # Adding noise


# Hypothesis Class: will start with a linear function, which is randomly initialized
# model is a variable of all parametesr, and supports model(X) calls
key, subkey = random.split(key)
model = eqx.nn.Linear(M, 1, use_bias = False, key = subkey)

# Needs to remove the non-differentiable parts of the "model" object
opt_state = optimizer.init(eqx.filter(model,eqx.is_inexact_array))

@eqx.filter_jit
def make_step(model, opt_state, X, Y):     
  def step_residuals(model):
    return residuals(model, X, Y)
  loss_value, grads = eqx.filter_value_and_grad(step_residuals)(model)
  updates, opt_state = optimizer.update(grads, opt_state, model, value = loss_value, grad = grads, value_fn = step_residuals)
  model = eqx.apply_updates(model, updates)
  return model, opt_state, loss_value

num_epochs = 20
batch_size = 1024#64
dataset = jdl.ArrayDataset(X,Y)
train_loader = DataLoaderJAX(dataset, batch_size = batch_size, shuffle = True)
for epoch in range(num_epochs):
    for X_batch, Y_batch in train_loader:
        model, opt_state, train_loss = make_step(model, opt_state, X_batch, Y_batch)
    
    if epoch % 2 == 0:
        print(f"Epoch {epoch},||theta - theta_hat|| = {jnp.linalg.norm(theta - model.weight)}")

print(f"||theta - theta_hat|| = {jnp.linalg.norm(theta - model.weight)}")


# ## Custom equinox type, like in pytorch
class MyLinear(eqx.Module):
    weight: jax.Array

    def __init__(self, in_size, out_size, key):
        self.weight = jax.random.normal(key, (out_size, in_size))

    # Equivalent to Pytorch's forward
    def __call__(self, x):
        return self.weight @ x

model = MyLinear(M, 1, key = subkey)
opt_state = optimizer.init(eqx.filter(model,eqx.is_inexact_array))

for epoch in range(num_epochs):
    for X_batch, Y_batch in train_loader:
        model, opt_state, train_loss = make_step(model, opt_state, X_batch, Y_batch)
    
    if epoch % 100 == 0:
        print(f"Epoch {epoch},||theta - theta_hat|| = {jnp.linalg.norm(theta - model.weight)}")

print(f"||theta - theta_hat|| = {jnp.linalg.norm(theta - model.weight)}")


model = eqx.nn.MLP(M, 1, width_size=128, depth=3, key = subkey)
opt_state = optimizer.init(eqx.filter(model,eqx.is_inexact_array))

for epoch in range(num_epochs):
    for X_batch, Y_batch in train_loader:
        model, opt_state, train_loss = make_step(model, opt_state, X_batch, Y_batch)
    
    if epoch % 2 == 0:
         print(f"Epoch {epoch},train_loss={train_loss}")
```

This particular error says
```
Traceback (most recent call last):
  File "c:\Users\jesse\Documents\GitHub\ECON622_instructor\lectures\examples\linear_regression_jax_equinox.py", line 97, in <module>
    model, opt_state, train_loss = make_step(model, opt_state, X_batch, Y_batch)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\equinox\_jit.py", line 242, in __call__
    return self._call(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\equinox\_module.py", line 1078, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\equinox\_jit.py", line 215, in _call
    out = self._cached(dynamic_donate, dynamic_nodonate, static)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jesse\Documents\GitHub\ECON622_instructor\lectures\examples\linear_regression_jax_equinox.py", line 50, in make_step
    updates, opt_state = optimizer.update(grads, opt_state, model, value = loss_value, grad = grads, value_fn = step_residuals)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\optax\transforms\_combining.py", line 73, in update_fn
    updates, new_s = fn(updates, s, params, **extra_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\optax\_src\base.py", line 330, in update
    return tx.update(updates, state, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\optax\_src\transform.py", line 1438, in update_fn
    diff_params = otu.tree_sub(params, state.params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jesse\anaconda3\envs\econ622\Lib\site-packages\optax\tree_utils\_tree_math.py", line 57, in tree_sub
    return jtu.tree_map(operator.sub, tree_x, tree_y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for -: 'custom_jvp' and 'NoneType'
```

**Comment by HarshBabla99** [comment]
I ran into the same issue. After some investigation, I may have some hints for what might be causing it. 

The problematic line in the error trace above (which I was able to replicate) is: 
```
diff_params = otu.tree_sub(params, state.params)
```
within `optax\_src\transform.py`


The issue is that `state.params` is "filtered" (using `eqx.filter(..., eqx.is_array)`), while `params` is not. This is evident if you print out both variables 

```
params = MLP(
  layers=[
    Linear(....),
    <wrapped function relu>,
    ...
  ]
)

state.params = MLP(
  layers=[
    Linear(....),
    None,
    ...
  ]
)
```

Therefore, one of the PyTrees has a `custom.jvp` (i.e. relu) at the same leaf-location where the other has a `NoneType`. This results in the eventual TypeError.

So I thought to fix it by filtering the model right before the update. I realize this is probably quite inefficient, but before I could even address that I received the following, fairly recondite, error traceback: 

```
.... (my code)    
    model_filtered = eqx.filter(model, eqx.is_array) #!
--> updates, opt_state = optimizer.update(grads, opt_state, model_filtered,
                                          value = loss_value, grad = grads, value_fn = loss)
    # Apply the updates to the model
    model = eqx.apply_updates(model, updates)

File python3.12/site-packages/optax/transforms/_combining.py:73, in chain.<locals>.update_fn(updates, state, params, **extra_args)
     71 new_state = []
     72 for s, fn in zip(state, update_fns):
---> 73   updates, new_s = fn(updates, s, params, **extra_args)
     74   new_state.append(new_s)
     75 return updates, tuple(new_state)

File python3.12/site-packages/optax/_src/linesearch.py:1493, in scale_by_zoom_linesearch.<locals>.update_fn(updates, state, params, value, grad, value_fn, **extra_args)
   1484 stepsize_guess = state.learning_rate
   1485 init_state = init_ls(
   1486     updates,
   1487     params,
   (...)
   1490     stepsize_guess=stepsize_guess,
   1491 )
-> 1493 final_state = jax.lax.while_loop(
   1494     cond_step_ls,
   1495     functools.partial(
   1496         step_ls, value_and_grad_fn=value_and_grad_fn, fn_kwargs=fn_kwargs
   1497     ),
   1498     init_state,
   1499 )
   1500 learning_rate = final_state.stepsize
   1501 scaled_updates = otu.tree_scalar_mul(learning_rate, updates)

    [... skipping hidden 9 frame]

File python3.12/site-packages/optax/_src/linesearch.py:1166, in zoom_linesearch.<locals>.step_fn(state, value_and_grad_fn, fn_kwargs)
   1159 def step_fn(
   1160     state: ZoomLinesearchState,
   1161     *,
   1162     value_and_grad_fn: Callable[..., tuple[chex.Numeric, base.Updates]],
   1163     fn_kwargs: dict[str, Any],
   1164 ) -> ZoomLinesearchState:
   1165   """Makes a step of the linesearch."""
-> 1166   new_state = jax.lax.cond(
   1167       state.interval_found,
   1168       functools.partial(
   1169           _zoom_into_interval,
   1170           value_and_grad_fn=value_and_grad_fn,
   1171           fn_kwargs=fn_kwargs,
   1172       ),
   1173       functools.partial(
   1174           _search_interval,
   1175           value_and_grad_fn=value_and_grad_fn,
   1176           fn_kwargs=fn_kwargs,
   1177       ),
   1178       state,
   1179   )
   1180   new_state = jax.lax.cond(
   1181       new_state.failed,
   1182       _try_safe_step,
   1183       lambda x: x,
   1184       new_state
   1185   )
   1186   return new_state

    [... skipping hidden 9 frame]

File python3.12/site-packages/optax/_src/linesearch.py:933, in zoom_linesearch.<locals>._zoom_into_interval(state, value_and_grad_fn, fn_kwargs)
    929 middle = jnp.where(use_bisection, middle_bisection, middle)
    931 # Check if new point is good
    932 _, value_middle, grad_middle, slope_middle = (
--> 933     _value_and_slope_on_line(
    934         value_and_grad_fn, params, middle, updates, fn_kwargs
    935     )
    936 )
    938 decrease_error = _decrease_error(
    939     middle, value_middle, slope_middle, value_init, slope_init
    940 )
    941 curvature_error = _curvature_error(slope_middle, slope_init)

File python3.12/site-packages/optax/_src/linesearch.py:637, in zoom_linesearch.<locals>._value_and_slope_on_line(value_and_grad_fn, params, stepsize, updates, fn_kwargs)
    598 r"""Compute value and slope on line.
    599 
    600 Mathematically, outputs
   (...)
    634       stepsize at the step.
    635 """
    636 step = otu.tree_add_scalar_mul(params, stepsize, updates)
--> 637 value_step, grad_step = value_and_grad_fn(step, **fn_kwargs)
    638 slope_step = otu.tree_vdot(grad_step, updates)
    639 return step, value_step, grad_step, slope_step

    [... skipping hidden 13 frame]

File python3.12/inspect.py:3273, in Signature.bind(self, *args, **kwargs)
   3268 def bind(self, /, *args, **kwargs):
   3269     """Get a BoundArguments object, that maps the passed `args`
   3270     and `kwargs` to the function's signature.  Raises `TypeError`
   3271     if the passed arguments can not be bound.
   3272     """
-> 3273     return self._bind(args, kwargs)

File python3.12/inspect.py:3186, in Signature._bind(self, args, kwargs, partial)
   3184                 msg = 'missing a required{argtype} argument: {arg!r}'
   3185                 msg = msg.format(arg=param.name, argtype=argtype)
-> 3186                 raise TypeError(msg) from None
   3187 else:
   3188     # We have a positional argument to process
   3189     try:

TypeError: missing a required argument: 'data'
```

**Comment by Michaelhess17** [comment]
Hello! I am having a similar problem! 

My code is essentially the same as both of yours. I also tried filtering the model before applying the updates. I first get an error from diffrax that the `Terms are not compatible with solver`. I figured I would just comment out this check to see what downstream error happens, but then unfortunately I get similar error to both of you that seems to be based on the filters not matching.

Here's my step function:
```python
def make_step(ti, yi, model, opt_state, seeding_steps):
      loss, grads = grad_loss(model, ti, yi, seeding_steps)
      grads = eqx.filter(grads, eqx.is_array)
      opt_state = eqx.filter(opt_state, eqx.is_array)
      model_ = eqx.filter(model, eqx.is_array)
      updates, opt_state = optim.update(grads, opt_state, model_, value=loss, grad=grads, value_fn=grad_loss, ti=ti, yi=yi, seeding_steps=seeding_steps)
      model = eqx.apply_updates(model_, updates)
```
After commenting out the term compatibility check, I get the following message:
```
File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/DDFA_NODE/ddfa_node/networks/jax_utils.py", line 259, in train_NODE
    loss, model, opt_state = make_step(_ts, yi, model, opt_state, seeding_steps)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/equinox/_jit.py", line 275, in __call__
    return self._call(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/equinox/_module.py", line 1096, in __call__
    return self.__func__(self.__self__, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/equinox/_jit.py", line 244, in _call
    marker, _, _ = out = self._cached(
                         ^^^^^^^^^^^^^
  File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/DDFA_NODE/ddfa_node/networks/jax_utils.py", line 219, in make_step
    updates, opt_state = optim.update(grads, opt_state, model_, value=loss, grad=grads, value_fn=grad_loss, ti=ti, yi=yi, seeding_steps=seeding_steps)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/optax/transforms/_combining.py", line 75, in update_fn
  updates, new_s = fn(updates, s, params, **extra_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/optax/_src/base.py", line 333, in update
  return tx.update(updates, state, params)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/mnt/Mouse_Face_Project/Desktop/Data/Python/NeuralODE/.pixi/envs/default/lib/python3.11/site-packages/optax/_src/transform.py", line 1658, in update_fn
  memory_idx = state.count % memory_size
               ~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'
```

I had this briefly working with optax==0.2.4.dev, but that was before the `value`, `grad`, and `value_fn` were required arguments for LBFGS. Here is the issue I created then that helped me solve the problem in the older version: [#1017] (https://github.com/google-deepmind/optax/issues/1017)

Hope this can get fixed soon! I would love to get my neural ODE models closer to local minima! I was pretty shocked at the loss curve in [this UDE showcase from SciML](https://docs.sciml.ai/Overview/dev/showcase/missing_physics/).

Thanks as always! :+1:

**Comment by johannahaffner** [comment]
Hi Michael, 

can you post a code snippet that can be run? Including imports, and as brief as possible, while still reproducing the error.

**Comment by Michaelhess17** [comment]
Ah I actually figured part of my problem out. I was using the code from that last [GitHub issue I mentioned](https://github.com/google-deepmind/optax/issues/1017) with mainly just this make_step function changed. I was however trying to use a linesearch, and it turns out that's causing the issue. If I set `linesearch=None` like the response to that last GitHub issue has, I don't have any issue. I think since I'm doing supervised learning, doing a linesearch doesn't make sense anyway!
Since the default for the `lfbgs` optimizer is to use a linesearch, this may be other people's issue, as well!

**Comment by johannahaffner** [comment]
Glad it is working, and good to know!

**Comment by schminin** [comment]
I have a follow-up question on this one: I'd like to include the linesearch and struggle to make it work (the only thing I've managed so far is to get from one error message to the next to the next...)

here's a minimal working example to reproduce the error message
`import jax
import jax.nn as jnn
import equinox as eqx
import diffrax
import jax.numpy as jnp
import optax
import jax.random as jr

class UDE_rhs(eqx.Module):
    mlp: eqx.nn.MLP        # Neural network modeling unknown dynamics
    log_gamma: jax.Array    # Learnable mechanistic parameter

    def __init__(self, *, key, **kwargs):
        super().__init__(**kwargs)
        self.mlp = eqx.nn.MLP(
            in_size=1,
            out_size=1,
            width_size=5,
            depth=2,
            activation=jnn.tanh,  # Smooth activation for continuous dynamics
            key=key,
        )
        self.log_gamma = jnp.array([-3.0])

    def __call__(self, t, y, args=None):
        # UDE dynamics = learned dynamics - some physical parameter
        return self.mlp(y) - jnp.exp(self.log_gamma) # TODO fix this


class NeuralUDE(eqx.Module):
    rhs: UDE_rhs
    solver: diffrax.AbstractSolver = eqx.field(static=True)
    rtol: float = eqx.field(static=True)
    atol: float = eqx.field(static=True)

    def __init__(self, *, key, solver_kwargs={"rtol": 1e-3, "atol": 1e-6}):
        self.rhs = UDE_rhs(key=key)
        self.solver = diffrax.Tsit5()
        self.rtol = solver_kwargs["rtol"]
        self.atol = solver_kwargs["atol"]

    def __call__(self, ts, y0):
        term = diffrax.ODETerm(self.rhs)
        solution = diffrax.diffeqsolve(
            term,
            self.solver,
            t0=ts[0],
            t1=ts[-1],
            dt0=ts[1] - ts[0],
            y0=y0,
            stepsize_controller=diffrax.PIDController(rtol=self.rtol, atol=self.atol),
            saveat=diffrax.SaveAt(ts=ts)
        )
        return solution.ys


# Dummy time series data
ts = jnp.linspace(0, 1, 10)
true_fn = lambda t: jnp.sin(2 * jnp.pi * t)
ys = true_fn(ts) + 0.1 * jax.random.normal(jax.random.PRNGKey(0), ts.shape)
y0 = ys[0:1]  # shape (1,)

# Instantiate the model
model = NeuralUDE(key = jr.PRNGKey(1))
# test forward step
model(ts, y0)

@eqx.filter_value_and_grad
def grad_loss(model, ts, ys_true):
    y0 = jnp.array([0.0])  # fixed initial condition
    y_pred = model(ts, y0)
    return jnp.mean((y_pred - ys_true) ** 2)

@eqx.filter_jit
def make_step(ti, yi, model, opt_state):
    loss, grads = grad_loss(model, ti, yi)
    grads = eqx.filter(grads, eqx.is_array)
    opt_state = eqx.filter(opt_state, eqx.is_array)
    model_ = eqx.filter(model, eqx.is_array)
    updates, opt_state = optim.update(grads, opt_state, model_)
    model = eqx.apply_updates(model, updates)
    return loss, model, opt_state

# This works
# optim = optax.lbfgs(learning_rate=1e-3, linesearch=None)
# The following doesn't:
optim = optax.lbfgs(learning_rate=1e-3)

opt_state = optim.init(eqx.filter(model, eqx.is_inexact_array))

for step in range(10):
    value, model, opt_state = make_step(ts, ys, model, opt_state)
    print(f"Step: {step}, Loss: {value}")
`

**Comment by patrick-kidger** [comment]
IIUC then the `updates, opt_state = optim.update(grads, opt_state, model_)` line is missing the `value`, `grad`, and `value_fn` arguments. :)

**Comment by schminin** [comment]
thank you for the fast reply. yes, that's what the error message says, but I struggle to find out how to define value_fn appropriately.

Adding ` updates, opt_state = optim.update(grads, opt_state, model_, value=loss, grad=grads, value_fn=grad_loss)` returns another error that two expected positional arguments (ts and y_true) are missing. 

In the example [here](https://optax.readthedocs.io/en/stable/_collections/examples/lbfgs.html) the value_fn expects the parameters as input, so I guess I also have to rewrite grad_loss in a way that it does not get model, ts, y_true as input, but only the parameters of the model. I guess I could define a new instance of the model with every function call, but that will probably be inefficient? Any recommendations on a smart way how to do this for a more complex PyTree structure?

**Comment by patrick-kidger** [comment]
I'm not sure I'm afraid :) This is a detail specific to Optax, not Equinox! The above is the limit of my knowledge with their library!

**Comment by buddy-finch** [comment]
I was having a similar problem using Jax and Flax. The way I got it to work was to pass through the variables that was needed in my function by using keyword arguments; ie, "def grad_loss(model, ts, ys_true, *args, **kwargs):"  and when you use the optim.update, add model=xxxxx, ts=xxxxx, ys_true=xxxx to the end. I'm not sure if the *args and **kwargs are needed in the function definition for grad_loss, but it doesn't hurt to have them in there. You will also have to pass the model twice, once for model_ and again for model=xxxxx, since the first will be stripped out by the update function for its use and it will not get passed to the grad_loss function.

updates, opt_state = optim.update(grads, opt_state, model_, value=loss, grad=grads, value_fn=grad_loss, model=?????, ts=?????, ys_true=?????).

You may get an error for passing duplicate arguments in the optim.update command since the update command has several keyword arguments that are required and you may accidentally use them again (ie. update uses a 'state' keyword where your positional argument of opt_state is at). If you do, then just rename the conflicting keyword name in your function.
